name: bookshelf
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.2+1
  flutter_rating_bar: ^3.2.0+1
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4
  cloud_firestore: ^0.14.4
  google_sign_in: ^4.5.6
  image_picker: ^0.6.0+9
  flutter_facebook_login: ^3.0.0
  modal_progress_hud: ^0.1.3
  fluttertoast: ^7.1.6
  percent_indicator: ^2.1.7+2
  advance_pdf_viewer: ^1.2.1+2
  pdf_text: ^0.4.0
  path_provider: ^1.6.27
  flutter_downloader: ^1.5.2
  permission_handler: ^5.0.1+1
  dio: ^3.0.10
  flutter_full_pdf_viewer: ^1.0.4
  pdf_flutter: ^1.1.4
  http: ^0.12.2
  syncfusion_flutter_pdf: ^18.4.41-beta
  syncfusion_flutter_pdfviewer: ^18.4.41-beta
  firebase_storage:
  sliding_up_panel: ^1.0.2
  cool_alert: ^1.0.3
  word_selectable_text: ^0.1.0
  textfield_search: ^0.7.0
  translator: ^0.1.5
  audioplayers: ^0.17.4
  speech_recognition: ^0.3.0
  speech_to_text: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/

  fonts:
    - family: Dandelion
      fonts:
        - asset: fonts/Dandelion.ttf

    - family: SegoeUI
      fonts:
        - asset: fonts/SEGOEUI.ttf

    - family: Ambili
      fonts:
        - asset: fonts/Ambili.ttf

    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Light.ttf

